// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package foobarbaz

import (
	"context"
)

// Injectors from wiress.go:

func InitializeBaz(ctx context.Context) (*Baz, error) {
	foo := ProvideFoo()
	bar := ProvideBar(foo)
	baz, err := ProvideBaz(ctx, bar)
	if err != nil {
		return nil, err
	}
	return baz, nil
}
